# Generated by Django 5.0.6 on 2024-06-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='title',
            field=models.CharField(default='Test', max_length=200),
            preserve_default=False,
        ),
    ]
